<?php

namespace AppBundle\Repository;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Update hijri date for all mosques
     */
    function updateHijriDate($adjustment)
    {
        $qb = $this->createQueryBuilder("c")
            ->update()
            ->set("c.hijriAdjustment", ":adjustment")
            ->set("c.updated", ":date")
            ->setParameters([
                ":adjustment" => $adjustment,
                ":date" => new \DateTime()
            ]);
        $qb->getQuery()->execute();
    }
}
