<?php

namespace AppBundle\Repository;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Update hijri date for all mosques
     */
    function updateHijriDate($data)
    {
        $qb = $this->createQueryBuilder("c")
            ->update()
            ->set("c.hijriAdjustment", ":adjustment")
            ->set("c.updated", ":date")
            ->setParameters([
                ":adjustment" => $data['hijriAdjustment'],
                ":date" => new \DateTime()
            ]);

        if ($data['country']) {
            $subQuert = $this->_em->createQueryBuilder()
                ->select('IDENTITY(m.configuration)')
                ->from('AppBundle:Mosque', 'm')
                ->where('m.country = :country');

            $qb->where($qb->expr()->in('c.id', $subQuert->getDQL()))
                ->setParameter(':country', $data['country']);
        }

        $qb->getQuery()->execute();
    }
}
