<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\DBAL\Types\Type;

/**
 * MosqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MosqueRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * 
     * @param User $user
     * @param string $search
     * @return \Doctrine\Common\Collections\ArrayCollection
     */
    function getMosquesByUser(User $user, $search) {
        $qb = $this->createQueryBuilder("m");

        if (!empty($search)) {
            $qb->andWhere("m.name LIKE :search "
                            . "OR m.associationName LIKE :search "
                            . "OR m.email LIKE :search "
                            . "OR m.address LIKE :search "
                            . "OR m.city LIKE :search"
                    )
                    ->setParameter(":search", "%$search%");
        }
        if (!$user->isAdmin()) {
            $qb->andWhere("m.user = :user_id")
                    ->setParameter(":user_id", $user->getId());
        }
        return $qb;
    }

    /**
     * get configured mosques with minimum one image set (image1)
     * @param integer $nbMax
     * @return array
     */
    function getConfiguredMosques($nbMax) {
        $qb = $this->createQueryBuilder("m")
                ->innerJoin("m.configuration", "c")
                ->where("m.image1 IS NOT NULL");

        if (is_numeric($nbMax)) {
            $qb->setMaxResults($nbMax);
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * set updated to now for all mosques
     */
    function forceYpdateAll() {
        $qb = $this->createQueryBuilder("m")
                ->update()
                ->set("m.updated", ":date")
                ->setParameter(":date", (new \DateTime())->format("Y-m-d h:i:s"));
        $qb->getQuery()->execute();
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->update("AppBundle:Configuration", "c")
                ->set("c.updated", ":date")
                ->setParameter(":date", (new \DateTime())->format("Y-m-d h:i:s"));
        $qb->getQuery()->execute();
    }

}
