<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * MosqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MosqueRepository extends \Doctrine\ORM\EntityRepository {

    function getMosquesByUser(User $user) {
        $qb = $this->createQueryBuilder("m");
        if (!$user->isAdmin()) {
            $qb->where("m.user = :user_id")
                    ->setParameter(":user_id", $user->getId());
        }
        return $qb->getQuery()->getResult();
    }

}
