#!/bin/bash

localUrl=http://localhost/mosquee/fr

if [ -f ~/Desktop/local_site.txt ]; then
    localUrl=`cat ~/Desktop/local_site.txt`
fi

chromium-browser --app=$localUrl --start-maximized &
sleep 30
xdotool key F11